from neuron.units import ms, mV, µm

#Per nueronal call defaults
SOMA_DIAMITER = 12.6157 * µm
DENDRITE_LENGTH = 200 * µm
DINDRITE_DIAMITER = 1 * µm

AXIAL_RESISTANCE = 100 #Ohm * cm
MEMBRANE_CAPACITANCE = 1 #micro farads / cm^2

SODIUM_CONDUCTANCE = 0.12 #S/cm2
POTASSIUM_CONDUCTANCE = 0.036 #S/cm2
LEAK_CONDUCTANCE = 0.0003 #s/cm2
REVERSEAL_POTENTIAL = -54.3 * mV
PASSIVE_CONDUCTANCE = 0.001 #S/cm2
LEAK_REVERSAL_POTENTIAL = -65 * mV